kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/paperplane-api
      tags: latest
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: ['paperplane.cc']
      user: ubuntu
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      source: ./docker-compose.yml
      target: /home/ubuntu/project-config/paperplane-api/docker-compose.yml
      script:
        - cd /home/ubuntu/project-config/paperplane-api
        - docker compose down || true
        - docker image rm paperplanecc/paperplane-api:latest || true
        - docker compose up -d

trigger:
  branch:
    - master
