kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: imagedir
        path: /imagedir
    commands:
      - docker build -t paperplanecc/paperplane-api:latest .
      - docker image save paperplanecc/paperplane-api:latest > /imagedir/paperplane-api.tar

  - name: prepare-docker
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - docker stop paperplane-api || true
        - docker rm paperplane-api || true
        - docker image rm paperplanecc/paperplane-api:latest || true
        - docker image load < /root/images-export/paperplane-api.tar

  - name: prisma-sync-db
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - cd /root/project-config/paperplane-api
        - docker run -t --rm --name paperplane-api-prisma --network root_default -e NODE_ENV=production --add-host=host.docker.internal:host-gateway -v ./.env.production:/app/.env.production:ro paperplanecc/paperplane-api:latest yarn dbdeploy:prod

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - cd /root/project-config/paperplane-api
        - docker compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: imagedir
    host:
      path: /root/images-export

trigger:
  branch:
    - master
