kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: jia-niang
      password:
        from_secret: GITEA_DOCKER_PUBLISH_TOKEN
      repo: jia-niang/paperplane-api
      tags: latest
      registry: git.paperplane.cc
      purge: false
      mirror: https://docker.mirrors.sjtug.sjtu.edu.cn

  - name: stop-service
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/paperplane-api
        - docker compose down || true
        - docker rm paperplane-api-prisma || true
        - docker image rm git.paperplane.cc/jia-niang/paperplane-api:latest || true
  
  - name: prisma-sync-db
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - cd /root/project-config/paperplane-api
        - docker pull paperplanecc/paperplane-api:latest
        - docker run -t --name paperplane-api-prisma --network root_default -e NODE_ENV=production --add-host=host.docker.internal:host-gateway -v ./.env.production:/app/.env.production:ro git.paperplane.cc/jia-niang/paperplane-api:latest yarn dbdeploy:prod
        - docker rm paperplane-api-prisma || true

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - docker image rm git.paperplane.cc/jia-niang/paperplane-api:latest || true
        - cd /root/project-config/paperplane-api
        - docker compose up -d

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
