# 本地运行专用 docker compose 文件
version: '3'

services:
  paperplane-api-local:
    image: paperplanecc/paperplane-api-base:latest
    container_name: paperplane-api-local
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '6100:6100'
    environment:
      - NODE_ENV=development
      - TZ=Asia/Shanghai
      - HOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    command: 'sh -c "yarn && yarn dev"'
